### ISSUE TITLE
Conda release?

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/membrane-curvature#107]
@ojeda-e with the amazing new release of `membrane-curvature` perhaps we can think about putting up a package on conda-forge? 

I would be happy to help you set it up, let me know. :)

**Comment by ojeda-e** [comment]
Thanks for this suggestion @hmacdope. I didn't include it in the to-do list for the 1.0.0 release because my understanding is that the package is not ready yet and it would need more work. Probably @orbeckst can confirm, but I thought I need to have the repo in a better shape. 

With that said, I am fully open to suggestions. I know there are some issues still open, and I will go back to them at some point. 

If a conda release with the current shape makes sense, I'll work on it as well. I just would like to have confirmation.

Thanks!

**Comment by orbeckst** [comment]
Definitely put up a conda-forge package. If you have a pypi release then also have a cf package.

**Comment by hmacdope** [comment]
I say go for it!

**Comment by hmacdope** [comment]
Let me know if you need a hand, the docs are [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#).

**Comment by ojeda-e** [comment]
Hi @hmacdope, sorry for the extremely late reply. There is one conda release available at the moment:
https://anaconda.org/conda-forge/membrane-curvature

However, this release had the dirty wheel that @IAlibay pointed out in #123. Probably we'll need a patch for this conda package after there is a clean wheel.

Commenting to stay on the same page.

**Comment by hmacdope** [comment]
No worries, I'll close this here.
